name: Vale Linter Update
description: The (un)official GitHub Action for Vale -- forked to update to Vale v2.3.x
author: makeworld-the-better-one
branding:
  icon: check
  color: green

inputs:
  styles:
    description: A list of styles to install prior to running Vale.
    required: false

  config:
    description: An externally-hosted configuration file to use.
    required: false

  files:
    description: 'The files to lint: "all" or "<some_folder>".'
    required: false
    default: all

  debug:
    description: 'Log debugging information to stdout'
    required: false
    default: 'false'

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.styles }}
    - ${{ inputs.config }}
    - ${{ inputs.files }}
    - ${{ inputs.debug }}
